frase = str(input('Digite uma frase: ')).strip()
frase = frase.upper()
print('A letra A aparece {} vezes'.format(frase.upper().count('A')))
print('A primeira letra A aparece na posição {}'.format(frase.find('A')+1))
print('A última letra A apareceu na posição {}'.format(frase.rfind('A')+1))